run:
  timeout: 5m
  tests: true
  skip-dirs:
    - "vendor"
    - "mocks"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - deadcode
    - ineffassign
    - structcheck
    - varcheck
    - gofmt
    - goimports
    - gocritic
    - gosimple
    - typecheck
    - depguard
    - revive
    - goconst
    - gosec
    - exportloopref
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: "ShopAvito"

  revive:
    severity: warning

  gosec:
    exclude:
      - G104 # Ignoring errors in defer functions
      - G601 # Implicit memory aliasing in range loop

  depguard:
    list-type: blacklist
    include-go-root: false
    rules:
      - pattern: "github.com/pkg/errors"
        allowed-patterns:
          - "errors"

  exportloopref:
    strict: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 5

output:
  format: tab
  print-issued-lines: true
  print-linter-name: true

# Настройка исключений для конкретных файлов/директорий
exclude-rules:
  - linters:
      - errcheck
      - staticcheck
    source: "^tests/"